# AWS environment variables (Used for EC2 installations)
aws_env_credentials:
  AWS_ACCESS_KEY_ID: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
  AWS_SECRET_ACCESS_KEY: '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'

# Mule Repository Credentials (used to pull the docker and mule images from Jfrog)
mule_repo_user: level1project
mule_repo_pass: level1project

# EC2 defaults
volumes:
  - device_name: /dev/xvda
    volume_type: gp2
    volume_size: 30
security_group_id: sg-b93036de #us-west-1
#security_group_id: sg-b327dfc2 #us-east-1
#security_group_id: sg-32915a5a #us-east-2
#image: ami-5ec1673e # Change the AMI, from which you want to launch the server Amazon Linux
#image: ami-7c22b41c # Change the AMI, from which you want to launch the server Ubuntu
image: ami-1da8f27d # Ubuntu in us-west-1
#image: ami-772aa961 # Ubuntu in us-east-1
#image: ami-25b69240 # Ubuntu in us-east-2
ec2_region: us-west-1 # Change the Region
keypair: interop-dev1 # Change the keypair name
vpc_subnet_id: subnet-a657b3fe #us-west-1a
#vpc_subnet_id: subnet-d975b790 #us-east-1b
#vpc_subnet_id: subnet-917c44db #us-east-2c
#vpc_subnet_id: subnet-be345fc8 #us-west-2a
#vpc_subnet_id: subnet-3963305d #us-west-2b
#vpc_subnet_id: subnet-95b207cd #us-west-2c
name_tag: demo

# Instance types:
instance_type: m4.xlarge
ist_ec2_type: '{{ instance_type }}'
dfsp_ec2_type: '{{ instance_type }}'
mgmt_ec2_type: '{{ instance_type }}'

# Instance counts
dfsp_ec2_count: 2
ist_ec2_count: 1
mgmt_ec2_count: 1

#Postgres Admin Accounts
ist_pg_user: istadmin
ist_pg_pass: istpass
dfsp_pg_user: dfspadmin
dfsp_pg_pass: dfsppass

#Other accounts
elasticpass: l1ppass
kibanapass: l1ppass
logstashpass: l1ppass
# kibana_user: kibanaadmin
# kibana_pass: l1p
cdir_pass: cVq8iFqaLuHy8jjKuA
cleg_pass: cVq8iFqaLuHy8jjKuA
ceur_pass: cVq8iFqaLuHy8jjKuA
sidecar_pass: 6dauAWcoeJuyRTFXH9
ckms_pass: central_kms

#DFSP Peer configuration
dfsp1_peer: dfsp2
dfsp2_peer: dfsp1

# Vagrantfile network setup (for local install only)
vagrant_net_type: public_network #public_network or private_network

#Kafka Metrics Reprting
metrics_host_port: ec2-35-164-199-6.us-west-2.compute.amazonaws.com:9092